[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.22"

[features]
resolution = true
skip-lint = false

[programs.devnet]
receipt_money = "ReMoLWd9XjJQTuSoT9tuKtfbjGy8FtVXX3dqgBHg1gy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = ".keys/admin.json"

[workspace]
members = ["programs/receipt_money"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
