[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.25"

[workspace]
members = ["programs/receipt-money"]

[features]
resolution = true
skip-lint = false

[programs.localnet]
receipto_fi = "35thGDc1684qSaXPYYmPgPTgtBfsY2B979g2wvrnndsE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
