[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.25"

[features]
resolution = true
skip-lint = false

[programs.devnet]
receipt_money = "RMcr2nvyrwCh89SvH47916S9TCvPkoGBPNR8E1d1LWa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = ".keys/admin.json"

[workspace]
members = ["programs/receipt_money"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
