[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.build_program]
script = """
RUSTUP_TOOLCHAIN="nightly-2024-11-19" anchor build
"""

[tasks.deploy_program]
script = """
cp .keys/receipt_money-keypair.json target/deploy/receipt_money-keypair.json
anchor deploy
"""
dependencies = ["build_program"]

[tasks.copy_files]
script = """
anchor idl upgrade -f target/idl/receipt_money.json RMcr2nvyrwCh89SvH47916S9TCvPkoGBPNR8E1d1LWa
cp target/idl/receipt_money.json simulation/targets/idl/receipt_money.json
cp target/types/receipt_money.ts simulation/targets/types/receipt_money.ts
cp target/types/receipt_money.ts simulation/src/types/receipt_money.ts
"""

[tasks.prerequisites]
script = """
solana-keygen new --outfile admin.json  
solana-keygen new --outfile receipt_money-buffer.json 
solana-keygen new --outfile receipt_money-program.json 
"""

[tasks.do_all]
dependencies = ["deploy_program", "copy_files"]
